### PR TITLE
Sprocket ANSI duplex 1 ½x1 *generator* sample added. Related to #335

### PR DESCRIPTION
**Pull request by hasecilu**
With almost 6GB in size the `FreeCAD-library/Mechanical Parts/Chains/` folder is the heavier one. Inside there are 32 sprocket and 14 plate folders folders with different versions on each one.

With the Configuration table, a new feature in FreeCAD 0.20 ([Read more here](https://wiki.freecadweb.org/Spreadsheet_Workbench#Configuration_tables)) we can unify the models created by type avoiding having one file for every count of teeth, i. e. one generator file instead of 33 files for 8 to 40 teeth.

I created one sample file (that could be used as a reference file) for the Sprocket ANSI duplex 1 ½x1 type and thanks to every file have it's data in a spreadsheet it was easy to gather all the data and create this file. With this we can remove 33 files that use 61.7MB and leave the generator file that uses 3.6MB.
Here is one video of the file:  https://youtu.be/ITaFcQATxqA

There are 1522 FCStd files using 2.1GB, if we create a generator file for every type (~165MB) we can save about 1.9GB in size.

~~The most tedious task is to manually gather the data from all the files...~~
I have just realized that you can copy the data from the tables inside the README files to a spreadsheet :man_facepalming: 

I tested the files in latest v0.21 and latest Link Branch and it's working.

Hi @pysimone, as you know more of these files than me, what do you think about this? are you interested in creating the other files?

Related to #335

### CODE REVIEW

**Comment by integrated-circuit** [comment]
> With almost 6GB in size the `FreeCAD-library/Mechanical Parts/Chains/` folder is the heavier one. Inside there are 32 sprocket and 14 plate folders folders with different versions on each one.
> 
> With the Configuration table, a new feature in FreeCAD 0.20 ([Read more here](https://wiki.freecadweb.org/Spreadsheet_Workbench#Configuration_tables)) we can unify the models created by type avoiding having one file for every count of teeth, i. e. one generator file instead of 33 files for 8 to 40 teeth.
> 
> I created one sample file (that could be used as a reference file) for the Sprocket ANSI duplex 1 ½x1 type and thanks to every file have it's data in a spreadsheet it was easy to gather all the data and create this file. With this we can remove 33 files that use 61.7MB and leave the generator file that uses 3.6MB. Here is one video of the file: https://youtu.be/ITaFcQATxqA
> 
> There are 1522 FCStd files using 2.1GB, if we create a generator file for every type (~165MB) we can save about 1.9GB in size.
> 
> ~The most tedious task is to manually gather the data from all the files...~ I have just realized that you can copy the data from the tables inside the README files to a spreadsheet man_facepalming
> 
> I tested the files in latest v0.21 and latest Link Branch and it's working.
> 
> Hi @pysimone, as you know more of these files than me, what do you think about this? are you interested in creating the other files?
> 
> Related to #335

+1 would be very usefull for End-user with limited storage

**Comment by luzpaz** [comment]
Lets open a forum thread to discuss the future of this repo. Any volunteers willing to open a thread?

CC @chennes the size issue of this repo is getting out of control again. Above are suggestions on how to curve some of it.

**Comment by pysimone** [comment]
Hi @hasecilu 
I think you had a great idea to reduce the size of this folder.
I'm definitely interested in contributing and creating the new files.
I'll do some tests in the next few days and I'll create the pull request.
Finally we could also delete the step files, do you agree?
Bye

**Comment by hasecilu** [comment]
> Lets open a forum thread to discuss the future of this repo. Any volunteers willing to open a thread?

Done, I made this post: https://forum.freecadweb.org/viewtopic.php?f=8&t=72634

**Comment by hasecilu** [comment]
> Finally we could also delete the step files, do you agree?
I think this would help a lot to reduce the size, check [the thread](https://forum.freecadweb.org/viewtopic.php?f=8&t=72634) to see if there are other opinions.

Also, note that the Body has it's name with an expression: `<<Sprocket ANSI duplex 1 ½x1 z%s>> % <<Data>>.z`, this way it gets renamed automatically respecting the number of teeth, useful if you need to export it.

**Comment by pysimone** [comment]
Hi
I did pull request [#375](https://github.com/FreeCAD/FreeCAD-library/pull/375) where there is only one FreeCAD file for Plate Wheel simplex 1 ½ x 1 with configuration table.
I erased all other FCstd files and all step files. This should drastically reduce the size of the folder.
If it's ok I will go on with the other folders: plate wheels, sprocket simplex, duplex, etc..

**Pull request merged**
